# Generated by Django 5.1.6 on 2025-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customer_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
