# Generated by Django 5.1.6 on 2025-02-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_customer_user_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
